### ISSUE TITLE
Python 2.7 not supported

### ISSUE THREAD

**Issue by sagism** [pythad/nider#11]
* nider version: 0.3.4
* Python version: 2.7.13
* Operating System: OSX

### Description
Running the example in the README.md, it fails due to colormap.py trying to import ChainMap which does not exist in python 2.7

### What I Did

I installed a polyfill and modified colormap.py but got more errors.
It's fine if you don't want to support Pyhton 2, but please mention that in the installation guide at least to save the pain from people. Thanks.

**Comment by pythad** [comment]
Thanks for mentioning this. I will add supported python versions to README.
